model: patchtst
patch_length: 2
patch_stride: 1
d_model: 64
num_attention_heads: 8
num_hidden_layers: 3
ffn_dim: 256
dropout: 0.25
norm_type: layernorm
head_dropout: 0.25
attention_dropout: 0.25
ff_dropout: 0.2
lr: 0.001
patience: 25
use_window_scaling: true
